"""PlatformIO pre-build script: gzip-bundles the web/ HTML files into a PROGMEM byte-array header.

Output: ``src/web/web_assets.h``.

``Import`` is a SCons builtin injected by PlatformIO when this script runs as
``extra_scripts = pre:tools/gen_web.py``; ruff sees it as undefined.
"""

import gzip
from pathlib import Path

Import("env")  # noqa: F821

WEB_DIR = Path("src/web")
OUT = WEB_DIR / "web_assets.h"

ASSETS: list[tuple[str, str]] = [
    ("LANDING_HTML", "landing.html"),
    ("EDITOR_HTML", "editor.html"),
    ("TRIGGERS_HTML", "triggers.html"),
]

CHUNK_BYTES = 16


def to_byte_array(name: str, raw: bytes) -> str:
    """Return a C++ byte-array literal for ``raw`` (gzipped) bound to symbols ``{name}_GZ`` and ``{name}_GZ_LEN``."""
    gz = gzip.compress(raw, compresslevel=9)
    lines = [
        f"// {name} - {len(raw)} bytes -> {len(gz)} gzipped",
        f"static const unsigned char {name}_GZ[] PROGMEM = {{",
    ]
    for i in range(0, len(gz), CHUNK_BYTES):
        chunk = ", ".join(f"0x{b:02x}" for b in gz[i : i + CHUNK_BYTES])
        lines.append("  " + chunk + ",")
    lines.append("};")
    lines.append(f"static const unsigned int {name}_GZ_LEN = {len(gz)};")
    return "\n".join(lines)


def build() -> None:
    """Bundle every asset in :data:`ASSETS` into ``OUT``."""
    parts: list[str] = [
        "// AUTOGENERATED by tools/gen_web.py - do not edit",
        "#pragma once",
        "",
    ]
    for name, file in ASSETS:
        path = WEB_DIR / file
        raw = path.read_bytes() if path.exists() else b"<!doctype html><title>placeholder</title>"
        parts.append(to_byte_array(name, raw))
        parts.append("")
    OUT.write_text("\n".join(parts))
    print(f"[gen_web] wrote {OUT}")


build()
