import gzip
import os
from pathlib import Path

Import("env")

WEB_DIR = Path("src/web")
OUT = WEB_DIR / "web_assets.h"

ASSETS = [
    ("LANDING_HTML",  "landing.html"),
    ("EDITOR_HTML",   "editor.html"),
    ("TRIGGERS_HTML", "triggers.html"),
]

def to_byte_array(name, raw):
    gz = gzip.compress(raw, compresslevel=9)
    lines = [f"// {name} - {len(raw)} bytes -> {len(gz)} gzipped"]
    lines.append(f"static const unsigned char {name}_GZ[] PROGMEM = {{")
    for i in range(0, len(gz), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in gz[i:i+16])
        lines.append("  " + chunk + ",")
    lines.append("};")
    lines.append(f"static const unsigned int {name}_GZ_LEN = {len(gz)};")
    return "\n".join(lines)

def build():
    parts = ["// AUTOGENERATED by tools/gen_web.py - do not edit", "#pragma once", ""]
    for name, file in ASSETS:
        path = WEB_DIR / file
        raw = path.read_bytes() if path.exists() else b"<!doctype html><title>placeholder</title>"
        parts.append(to_byte_array(name, raw))
        parts.append("")
    OUT.write_text("\n".join(parts))
    print(f"[gen_web] wrote {OUT}")

build()
